### ISSUE TITLE
Protecting the docker daemon using CA in ubuntu

### ISSUE THREAD

**Issue by hamidasgarian** [nicholasdille/DockerTLS-MicrosoftCA#1]
i want to secure my docker in ubuntu to restrict access from outside.
i follow your instruction in windows. put 3 .pem files in path and change my daemon.json as below:

{
   "tlskey":    "/home/server/secure-docker/server-key.pem",
   "tlsverify": true,
   "tlscacert": "/home/server/secure-docker/ca.pem",
   "tlscert":   "/home/server/secure-docker/server-cert.pem",
   "bip": "12.12.12.12/24" ,
   "hosts": ["tcp://0.0.0.0:2376", "unix:///var/run/docker.sock"],
   "storage-driver": "overlay2",
   "debug": true 
}

all work in server side is that?
in client what works must do?
what command to connect to my docker from clients?

very appreciated

**Comment by nicholasdille** [comment]
For connecting to the Docker host secured using TLS certificates, your clients needs a client certificates originating from the same CA as the server certificate. I have explained the steps in my post http://dille.name/blog/2016/11/08/using-a-microsoft-ca-to-secure-docker/. You can also extract the files from `~\.docker`.
